window.opacity = 1

[colors.primary]
background = '#f8f8f8'
foreground = '#2a2b33'

[colors.normal]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#bbbbbb'

[colors.bright]
black   = '#000000'
red     = '#de3d35'
green   = '#3e953a'
yellow  = '#d2b67b'
blue    = '#2f5af3'
magenta = '#a00095'
cyan    = '#3e953a'
white   = '#ffffff'

[font]
size = 6
normal = { family="JetBrainsMono Nerd Font", style="Regular" }
bold = { family="JetBrainsMono Nerd Font", style="Bold" }
italic = { family="JetBrainsMono Nerd Font", style="Italic" }
bold_italic = { family="JetBrainsMono Nerd Font", style="Bold Italic" }

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"
